config/routes.rb
Ahrlty::Application.routes.draw do
  mount StyleGuide::Engine => "/style-guide"
  root "listings#sales"

  get "sales", to: "listings#sales", format: false, as: "sales"
  get "rentals", to: "listings#rentals", format: false, as: "rentals"

  get "contact", to: "pages#contact"

  ActiveAdmin.routes(self)
  get 'listing/:code', to: "listings#show", format: false, as: "listing"

  devise_for :users,
    :path_names => { :sign_in => 'login', :sign_out => 'logout' },
    :controllers => { :omniauth_callbacks => "omniauth_callbacks" },
    :skip => [:registration]
end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :listing
  acts_as_list scope: :listing

  has_attached_file :gallery_image,
    styles: {
      lightbox: "500x500>",
      medium: "375x375>",
      thumb: "250x250>"
    }

  validates_attachment_content_type :gallery_image, content_type: /\Aimage\/.*\Z/
  validates :gallery_image, presence: true

  def self.sorted
    order(:position)
  end

end

app/models/listing.rb
class Listing < ActiveRecord::Base

  belongs_to :neighborhood

  LISTING_TYPES = ["House", "Condo", "Co-op", "Rental House", "Rental Apartment"]
  STATUSES = ["Available", "In Contract", "Rented", "Sold"]

  has_many :images
  has_many :open_houses
  belongs_to :user

  has_attached_file :headline_image, {
    styles: {
      listing: "300x300>",
      lead: "360x360>",
      thumb: "200x200>"
    },
    default_url: "/images/:class/:style.png"
  }

  validates_attachment_content_type :headline_image, content_type: /\Aimage\/.*\Z/
  validates :headline_image, presence: true

  validates :listing_type, presence: true
  validates :listing_type, inclusion: { in: LISTING_TYPES }
  validates :headline, presence: true
  validates :description, presence: true
  validates :listing_page_headline, presence: true
  validates :listing_page_description, presence: true
  validates :code, presence: true
  validates :code, uniqueness: true
  validates :status, presence: true

  before_validation :check_code

  def to_param
    code
  end

  def rental?
    return true if self.listing_type == "Rental House" || self.listing_type == "Rental Apartment"
  end

  def sale?
    return true if self.listing_type == "House" || self.listing_type == "Condo" || self.listing_type == "Coop"
  end

  def ispublished?
    self.publish
  end

  def self.condos_and_coops
    where(listing_type: ["Condo", "Co-op"]).published?.order(updated_at: :desc)
  end

  def self.rentals
    where(listing_type: ["Rental House", "Rental Apartment" ]).published?.order(updated_at: :desc)
  end

  def self.houses
      where(listing_type:"House").published?.order(updated_at: :desc)
  end

  def self.sales
    where(listing_type: ["House", "Condo", "Co-op"])
  end

  def self.published?
    where(publish: true)
  end

  def self.unpublished?
    where(publish: false)
  end

  def self.statuses
    STATUSES
  end

  def self.listing_types
    LISTING_TYPES
  end

  def self.publish_options
    PUBLISH_OPTIONS
  end

  def check_code
    return if self.code.present?
    self.code = generate_code
    while Listing.find_by(code: self.code)
      self.code = randomize_code
    end
  end

  def randomize_code
    return nil if self.listing_type.blank?
    "#{self.listing_type[0]}-#{[*0..10000].sample}R"
  end

  def generate_code
    return nil if self.listing_type.blank?
    letter = self.listing_type[0]
    latest_code = Listing.maximum(:id) || 0
    "#{letter}-#{latest_code + 1}"
  end

  def display_name
    code
  end
end

app/models/neighborhood.rb
class Neighborhood < ActiveRecord::Base
has_many :listings

end

app/models/open_house.rb
class OpenHouse < ActiveRecord::Base
  belongs_to :listing

  just_define_datetime_picker :start_time
  just_define_datetime_picker :end_time

  validates :start_time, presence: true
  validates :end_time, presence: true

  def self.upcoming
    current_thursday = Chronic.parse("thursday").beginning_of_day
    today = Time.now.beginning_of_day

    where('start_time >= ?', today).where('end_time < ?', current_thursday)
  end

  def human_start_time
    start_time.strftime("%A %B %d, %Y %I:%M%p")
  end

  def human_end_time
    end_time.strftime("%A %B %d, %Y %I:%M%p")
  end

  def lead_page_time
    "#{start_time.strftime("%A, %B %d %I:%M%p")} - #{self.end_time.strftime("%I:%M%p")}"
  end

  def published_listing
    listing.publish == true
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :rememberable, :trackable,
         :omniauthable, omniauth_providers: [:google_oauth2]
  has_many :listings

  # :email, :password, :password_confirmation, :remember_me, :avatar, :name

  validates :email, presence: true, uniqueness: true

  def self.find_or_create_google(auth_hash)
    user = where(email: auth_hash[:info][:email]).first_or_create! do |u|
      u.password = Devise.friendly_token[0,20]
    end
    user.name = auth_hash[:info][:name]
    user.avatar = auth_hash[:info][:image]
    user.save if user.changed?
    user
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def authenticate_user!
    redirect_to user_omniauth_authorize_path(:google_oauth2) unless user_signed_in?
  end

  def after_sign_in_path_for(user)
    # this isn't set - maybe we can work somethign up in the session
    # return request.env['omniauth.origin'] if request.env['omniauth.origin']
    return admin_root_path
  end

end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController

  def sales
    @houses = Listing.houses
    @condos_and_coops = Listing.condos_and_coops
  end

  def rentals
    @rentals = Listing.rentals
  end

  def show
    @listing = Listing.find_by(code: params[:code], publish: true)
    @agent = User.find_by(id: @listing.user_id) if @listing
    return not_found unless @listing

    if @listing.rental?
      render '_rentalshow.html.erb'
    elsif @listing.sale?
      render '_saleshow.html.erb'
    end
  end

  private

  def not_found
    render '_unavailable.html.erb'
  end

  def listing_params
    params.require(:listing).permit(:listing_type, :status, :publish, :headline, :sub_headline, :description, :listing_page_headline, :listing_page_description, :price)
  end

end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  before_filter :check_domain

  def google_oauth2
    @user = User.find_or_create_google(auth_info)
    return redirect_to :root, error: @user.errors.full_messages.to_sentence unless @user.valid?
    return sign_in_and_redirect @user, :event => :authentication
  end

  private

  def check_domain
    users_domain = auth_info[:extra][:raw_info][:hd]
    unless authorized_domains.include?(users_domain)
      flash[:notice] = "You're Google Account is not allowed to log into this application."
      return redirect_to :root
    end
  rescue NoMethodError
    flash[:notice] = "Something went wrong while logging you in."
    return redirect_to :root
  end

  def authorized_domains
    ENV['AUTHORIZED_DOMAINS'].split(',')
  end

  def auth_info
    request.env["omniauth.auth"]
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def contact
  end

end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController

  def index
    @houses = Property.houses.order("updated_at desc")
    @condos_coops = Property.where(property_type: ['condo', 'co-op']).order("updated_at desc")
  end

  def show
    @property = Property.find(params[:id])
  end

end

app/controllers/styleguides_controller.rb
class StyleguidesController < ApplicationController

  def styles
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/images/_image.html.erb
<%= content_tag_for :li, image do %>
  <%= link_to "Delete", admin_image_path(image), method: :delete %></br>
  <%= image_tag(image.gallery_image.url(:thumb)) %>
<% end %>

app/views/admin/listings/_gallery.html.erb
<ul class="js-images" data-sort-url="<%= sort_admin_listing_images_url(listing) %>">
  <%= button_to("Add Image", new_admin_listing_image_path(listing), method: :get, class: "add-image-button") %>
  <%= render listing.images.sorted %>
</ul>

app/views/admin/listings/_open_houses.html.erb
<div class= "row">
  <div class="col-md-3">
    <%= render listing.open_houses%>
  </div>
</div>

app/views/admin/open_houses/_open_house.html.erb
<div class= "row">
  <div class="col-md-3">
    <h4><b>Start time: </b><%="#{open_house.start_time.strftime("%A %B %d, %Y %I:%M%p")}" %>  <b>End time: </b><%= "#{open_house.end_time.strftime("%A %B %d, %Y %I:%M%p")}" %></h4>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ahrlty</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'shared/flash' unless flash.empty? %>
  <%= render 'shared/nav' %>

  <%= yield %>

</body>
</html>

app/views/listings/_listing.html.erb
<div class='listing-box js-listing-box'>
  <% if listing.open_houses.upcoming.any? %>
    <div class="open-house-headline">
      <h2> Open House </h2>
        <% listing.open_houses.upcoming.each do |open_house| %>
          <p> <%= open_house.lead_page_time %></p>
        <% end %>
      <p><%= listing.street_address %>, at (<%= listing.cross_streets %>)</p>
    </div>
  <% end %>
  <% unless listing.status == "Available" %>
    <h1 class="sold"><%= listing.status.upcase %></h1>
  <% end %>
  <h3 class="sub-headline"><%= listing.sub_headline %></h3>
  <%= link_to image_tag(listing.headline_image(:lead), class: 'listing-box-image'),listing %>
  <h2 class="headline"><%= link_to listing.headline, listing %></h2>
  <p class="description"><%=  listing.description %> - $<%= listing.price%></p>
  <p>
    <% if listing.rental? && listing.user %>
      Email <%= mail_to listing.user.email, listing.user.name %> or call <span class="highlight"><%= listing.user.phone %></span> or
    <% end %>
    Call <span class="highlight">(718) 788-8200</span> to see <span class="highlight"><%= listing.code %></span> Email <%= mail_to "Sales7@AHRlty.com", "Sales7@AHRlty.com" %>
  </p>
</div>

app/views/listings/_rentalshow.html.erb
<div class="container">
  <div class="row">

    <div class="col-md-8">
      <div class="row">
        <% @listing.images.sorted.each do |image| %>
          <div class="col-md-4">
            <%= link_to image_tag(image.gallery_image(:thumb), alt: "gallery_image", class: "listing-image"),image.gallery_image(:lightbox), rel: :lazybox %>
          </div>
        <% end %>
      </div>
    </div>

    <div class="col-md-4">
      <div class="row">
        <div class="col-md-12">
          <h1 class="blue"><%= @listing.headline %></h1>
          <h3 class="blue"><%= "#{@listing.neighborhood.name} - " if @listing.neighborhood %><%= @listing.price %></h3>
          <p><%= @listing.description %></p>
          <% if @agent %>
            <ul class ="rental-listing">
              <li><b>Broker:</b> <%= @agent.name %></li>
              <li><b>Phone:</b> <%= @agent.phone %></li>
              <li><b>Email:</b> <%= mail_to @agent.email%></li>
              <li><b>Listing:</b> <%= @listing.code %></li>
            </ul>
          <% end %>
        </div>
      </div>
    </div>

  </div>
</div>

app/views/listings/_saleshow.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12 open-house-info">
    <% if @listing.open_houses.upcoming.any? %>
      <h2>Open House</h2>
      <% @listing.open_houses.upcoming.each do |oh|%>
        <p><%= oh.lead_page_time %></p>
        <% end %>
        <p><%= @listing.street_address %>, at (<%= @listing.cross_streets %>)</p>
      <% end %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <div class="underline">
        <h3 class="blue centered"><%= "#{@listing.neighborhood.name}, " if @listing.neighborhood %><%= "#{@listing.bedrooms}, bedrooms" if @listing.bedrooms %><%= @listing.listing_type %></h3>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12">
        <h1 class="blue centered"><%= @listing.headline %></h1>
      </div>
    </div>
  </div>
  <div class="row">
    <% @listing.images.sorted.each do |image| %>
      <div class="col-md-4">
        <%= link_to image_tag(image.gallery_image(:medium), alt: "gallery image", class: "listing-image"), image.gallery_image(:lightbox), rel: :lazybox %>
      </div>
    <% end %>
  </div>
  <div class="row">
    <div class="col-md-10 col-md-offset-1">
      <p><%= @listing.description %> Asking price: $<%= @listing.price %>!</p>
      <h2 class="centered"> To see this property call Aguayo & Huebener at (718) 788-8200
        <% if @agent%>
          <%= "& ask for #{@agent.name},"%>
            <%unless @agent.phone.nil? %>
              <%=" cell: #{@agent.phone}"%>
            <% end %> about <%= @listing.code %>
        <% end %>
      </h2>
      <p class="centered">Or e-mail us at <%= mail_to "Sales7@AHRlty.com", "Sales7@AHRlty.com" %>(For the quickest response please include your name and phone number.) If you've been in contact with one of our agents, please call that agent to see this property.</p>
    </div>
  </div>
</div>

app/views/listings/_unavailable.html.erb
<div class="col-sm-6 col-sm-offset-3 dialog">
  <h1>This listing has been removed, please contact Aguayo & Huebener for more information.</h1>
  <p>You may have mistyped the address or the page may have moved.</p>
  <%= link_to "Return to the Homepage", root_path %>
</div>

app/views/listings/rentals.html.erb
<div class="container">
  <div class="row">
    <div>
      <div class="rentals-column rentals-index">
        <h3 class="sales-column-header">Rentals</h3>
        <div class="js-rentals-container rentals-container">
          <%= render @rentals %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/listings/sales.html.erb
<div class="container">

  <div class="row">

    <div class="col-md-4 col-md-offset-2">
      <div class="sales-column">
        <h3 class="sales-column-header">HOUSES: PARK SLOPE &amp; VICINITY</h3>
        <%= render @houses %>
      </div>
    </div>

    <div class="col-md-4">
      <div class="sales-column">
        <h3 class="sales-column-header">CO-OPS/CONDOS: PARK SLOPE &amp; VICINITY</h3>
        <%= render @condos_and_coops %>
      </div>
    </div>

  </div>

</div>

app/views/shared/_flash.html.erb
<div class="container">
  <% flash.each do |name, msg| -%>
    <%= content_tag :div, msg, class: name %>
  <% end -%>
</div>

app/views/shared/_nav.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10 col-md-offset-1">
      <div class="nav_logo">
        <%= image_tag "header.jpg",  alt: "Aguayo & Huebner Realty" %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <ul class="navigation">
        <li class="sales"><%= link_to "Sales", sales_path %></li>
        <li class="rentals"><%= link_to "Rentals", rentals_path %></li>
        <li class="contact"><%= link_to "Contact", contact_path %></li>
      </ul>
    </div>
  </div>
</div>

app/views/style-guide/branding/_colors.html.erb
<div class="row">
  <div class="col-md-12">
    <p>Don't use these classes unless you need background colors. For reference only.</p>
    <ul>
      <li class="white">AG White</li>
      <li class="gray">AG Gray</li>
      <li class="dk-gray">AG Dark Gray</li>
      <li class="black">AG Black</li>
      <li class="red">AG Red</li>
      <li class="dk-red">AG Dark Red</li>
      <li class="peach">AG Peach</li>
      <li class="blue">AG Blue</li>
      <li class="purple">AG Purple</li>
      <li class="brown">AG Brown</li>
    <ul>
  </div>
</div>

app/views/style-guide/branding/_tags.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="sold">SOLD</div>
    <div class="contract">IN CONTRACT</div>
  </div>
</div>

app/views/style-guide/buttons/_buttons.html.erb
<div class="row">
  <div class="col-md-12">
   <div class="btn">Button</div>
   <div class="btn btn-red">Red Button</div>
   <div class="btn btn-black">Black Button</div>
   <div class="btn btn-gray">Gray Button</div>
  </div>
</div>

app/views/style-guide/components/_listings.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="sales-column">
      <h1>This is the sales column</h1>
        <h1 class="sales-column-header">Sales Column Header</h1>
        <div class="listing-box">
          <h1>This is the listing box</h1>
          <h1 class="sub-headline">Sub Headline</h1>
          <img class="listing-box-image" src="http://placekitten.com/200/200" />
          <h1 class="listing-box headline"> Nested Listing Box Headline</h1>
          <h1>With a <a class="headline">Link!</a></h1>
            <div class="description">
              <p>I'm assuming this is a paragraph of some sort describing a wonderful home.</p>
              <p class="highlight">And this is the highlight paragraph.  Booyah!</p>
            </div>
        </div>
    </div>
  </div>
</div>

app/views/style-guide/components/_nav.html.erb
  <div class="row">
    <div class="col-md-10 col-md-offset-1">
      <div class="nav_logo">
        <img src="http://placekitten.com/200/200" />
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <ul class="navigation">
        <li class="home"><a href="#">Sales</a></li>
        <li class="rentals"><a href="#">Rentals</a></li>
        <li class="contact"><a href="#">Contact</a></li>
      </ul>
    </div>
  </div>

app/views/style-guide/components/_tags.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="sold">SOLD</div>
    <div class="contract">IN CONTRACT</div>
  </div>
</div>

app/views/style-guide/typography/_words.html.erb
<div class="row">
  <div class="col-md-4">
    <h1>h1</h1>
    <h2>h2</h2>
    <h3>h3</h3>
    <h4>h4</h4>
    <h5>h5</h5>
    <h6>h6</h6>
  </div>
   <div class="col-md-4">
    <h1 class="emphasis">h1 emphasis</h1>
    <h2 class="emphasis">h2 emphasis</h2>
    <h3 class="emphasis">h3 emphasis</h3>
    <h4 class="emphasis">h4 emphasis</h4>
    <h5 class="emphasis">h5 emphasis</h5>
    <h6 class="emphasis">h6 emphasis</h6>
  </div>
   <div class="col-md-4">
    <h1 class="blue">h1 blue</h1>
    <h2 class="blue">h2 blue</h2>
    <h3 class="blue">h3 blue</h3>
    <h4 class="blue">h4 blue</h4>
    <h5 class="blue">h5 blue</h5>
    <h6 class="blue">h6 blue</h6>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <h1> Normal Paragraph</h1>
    <p>Cupcake ipsum dolor sit amet wafer apple pie halvah chocolate. Candy halvah cotton candy dessert topping soufflé biscuit. Pie tootsie roll jelly beans bonbon. Dragée chupa chups gummi bears sesame snaps.</p>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <h1>Address Paragraph</h1>
    <p class="address">Cupcake ipsum dolor sit amet wafer apple pie halvah chocolate. Candy halvah cotton candy dessert topping soufflé biscuit. Pie tootsie roll jelly beans bonbon. Dragée chupa chups gummi bears sesame snaps.</p>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <h1>Schedule Notice Paragraph</h1>
    <p class="schedule-notice">Cupcake ipsum dolor sit amet wafer apple pie halvah chocolate. Candy halvah cotton candy dessert topping soufflé biscuit. Pie tootsie roll jelly beans bonbon. Dragée chupa chups gummi bears sesame snaps.</p>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <h1>Centered Paragraph</h1>
    <p class="center-text">Cupcake ipsum dolor sit amet wafer apple pie halvah chocolate. Candy halvah cotton candy dessert topping soufflé biscuit. Pie tootsie roll jelly beans bonbon. Dragée chupa chups gummi bears sesame snaps.</p>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <h1>Links</h1>
    <p>Your link is <a href="#">RIGHT HERE</a></p>
  </div>
</div>